#!/usr/bin/env python

GATE_PASS_DEPTH = -1

PATH_DETECTING_DEPTH = -1

BOUY_DETECTING_DEPTH = -2
BOUY_YELLOW_PULL_DEPTH = -3

NAV_TOP_DETECTING_DEPTH = -2.6
NAV_BOT_DETECTING_DEPTH = -2
NAV_ROLL_DEPTH = -2

BIN_DETECTING_DEPTH = -1
BIN_DROP_DEPTH = -2.5

SET_DETECTING_DEPTH = -1.5

PING_DETECTING_DEPTH = -1
PING_FLOATING_DEPTH = 0.1

FINISH = 0.1
