source /opt/ros/kinetic/setup.bash
source ~/catkin_ws/devel/setup.bash
export BLUEVIEW_SDK_ROOT="/home/zeabus/bvtsdk"

alias edit_alias='nano ~/.bash_aliases; source ~/.bash_aliases;'
alias edit_bashrc='nano ~/.bashrc; source ~/.bashrc;'

alias catkin_source='source ~/catkin_ws/devel/setup.bash; cd ~/catkin_ws; rospack profile; cd -;'
alias catkin_everywhere='cd ~/catkin_ws; catkin_make; cd -; catkin_source'
alias cdcatkin='cd ~/catkin_ws'

alias open_camera='roslaunch zeabus_vision open_camera.launch'
alias controller='roslaunch zeabus_controller control.launch'
alias minimal='roslaunch zeabus_bringup minimal.launch'
alias localization='roslaunch zeabus_bringup zeabus_dvl_localize.launch'
alias ui='roslaunch zeabus_ui ui.launch'
alias joy_ctrl='roslaunch zeabus_teleop joy_F710.launch'
alias joy_thruster='roslaunch zeabus_teleop joy_F710_thruster.launch'

alias sshzeabus00='ssh zeabus@zeabus00 -p 22 -X'
alias sshzeabus01='ssh zeabus@zeabus01 -p 22 -X'

alias roslocal='export ROS_MASTER_URI=http://localhost:11311/;'
alias roszeabus00='export ROS_MASTER_URI=http://zeabus00:11311/;'
alias roszeabus01='export ROS_MASTER_URI=http://zeabus01:11311/;'
alias rosme='export ROS_MASTER_URI=http://192.168.1.69:11311/;'

alias accessport='sudo chmod 666 /dev/ttyUSB0'

alias calibrate='rosrun camera_calibration cameracalibrator.py --size 8x6 --square 0.055 right:=/rightcam_top/image_raw left:=/leftcam_top/image_raw right_camera:=/rightcam_top left_camera:=/leftcam_top'

alias cam_record_top='rosbag record /top/center/image_rect_color/compressed'
alias cam_record_bottom='rosbag record /bottom/left/image_raw/compressed'

roslocal
#roszeabus00
#catkin_source
#accessport
#rosme
#roszeabus01








